proton: ServiceSpec
pipeline:
  service_dir: ecs-ping-sns
  dockerfile: Dockerfile
  unit_test_command: echo 'add your unit test command here'
instances:
  - name: scheduled-fargate-svc-prod
    environment: fargate-env-prod
