schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EC2EnvironmentInput"
  types:
    EC2EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_cidr:
          type: string
          description: "This CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_one_cidr:
          type: string
          description: "The CIDR range for public subnet one"
          default: 10.0.0.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_two_cidr:
          type: string
          description: "The CIDR range for public subnet two"
          default: 10.0.64.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_one_cidr:
          type: string
          description: "The CIDR range for private subnet one"
          default: 10.0.128.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_two_cidr:
          type: string
          description: "The CIDR range for private subnet two"
          default: 10.0.192.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        subnet_type:
          type: string
          description: "Subnet type for your EC2 instances"
          enum: ["public", "private"]
          default: "public"
        DesiredCapacity:
          type: number
          default: 1
          description: "Number of EC2 instances to launch in your ECS cluster."
        MaxSize:
          type: number
          default: 6
          description: "Maximum number of EC2 instances that can be launched in your ECS cluster."
        ECSAMI:
          description: "AMI ID"
          type: string
          default: "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id"
        InstanceType:
          description: "EC2 instance type"
          type: string
          default: "c4.xlarge"