schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_cidr:
          title: "VPC CIDR"
          type: string
          description: "This CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        public_subnet_one_cidr:
          title: "Public subnet one CIDR"
          type: string
          description: "The CIDR range for public subnet one"
          default: 10.0.1.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        public_subnet_two_cidr:
          title: "Public subnet two CIDR"
          type: string
          description: "The CIDR range for public subnet one"
          default: 10.0.2.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        private_subnet_one_cidr:
          title: "Private subnet one CIDR"
          type: string
          description: "The CIDR range for private subnet one"
          default: 10.0.3.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        private_subnet_two_cidr:
          title: "Private subnet two CIDR"
          type: string
          description: "The CIDR range for private subnet two"
          default: 10.0.4.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        service_discovery_namespace:
          title: "Service discovery namespace"
          type: string
          description: "The name of the private namespace for service discovery"
          default: example.local
