schema:
  format:
    openapi: "3.0.0"
  service_input_type: "PrivateServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    PrivateServiceInput:
      type: object
      description: "Input properties for a Private Fargate service"
      properties:
        port:
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        desired_count:
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: [ "medium", "large", "x-large"]
          default: "medium"
        image:
          type: string
          description: "The name/url of the container image"
          default: "mcr.microsoft.com/dotnet/framework/samples:aspnetapp"
          minLength: 1
          maxLength: 200
        service_discovery_name:
          type: string
          description: "The name of the service to register in service discovery"
          minLength: 3
          maxLength: 24
      required:
        - service_discovery_name

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        cluster_operating_system_family:
          type: string
          description: "The operating system used for the ECS Task Definition"
          default: WINDOWS_SERVER_2019_CORE
          enum: ['WINDOWS_SERVER_2019_CORE', 'WINDOWS_SERVER_2019_FULL', 'WINDOWS_SERVER_2022_CORE', 'WINDOWS_SERVER_2022_FULL']
        build_server_ami_id:
          type: string
          description: SSM Parameter expression to use to retrieve the AMI ID for the build server. Must be compatible with operating system version used by ECS cluster.
          default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Core-ECS_Optimized/image_id
        build_server_instance_type:
          type: string
          description: "Instance type used for the EC2 Instance that serves as the build server."
          default: t2.medium
          enum: [t2.small, t2.medium, t2.large, 
                 t3.small, t3.medium, t3.large,
                 t3a.small, t3a.medium, t3a.large ]
        build_server_volume_size:
          type: number
          description: "Volume size in GiBs used when provisioning the build server."
          default: 30
          minimum: 4
          maximum: 1024
        build_server_volume_type:
          type: string
          description: "Volume type used when provisioning the build server."
          default: gp3
          enum: [ gp3, gp2 ]
        dockerfile:
          type: string
          description: "The location of the Dockerfile to build"
          default: "Dockerfile"
          minLength: 1
