proton: ServiceSpec
pipeline:
  code_dir: lambda-worker
  unit_test_command: echo 'add your unit test command here'
  packaging_command: zip function.zip app.js
instances:
  - name: worker-lambda-svc-prod
    environment: vpc-env-prod
