schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      required:
        - ttl_attribute
      properties:
        ttl_attribute:
          title: "TTL attribute"
          type: string
          description: "Which attribute to use as the TTL attribute"
          default: ttl
          minLength: 1
          maxLength: 100
