schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    LoadBalancedServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        desired_count:
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          type: string
          description: "The name/url of the container image"
          minLength: 1
          maxLength: 200
        service_discovery_name:
          type: string
          description: "The name of the service to register in service discovery"
          minLength: 3
          maxLength: 24
      required:
        - image
        - service_discovery_name

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        build_server_ami_id:
          type: string
          description: AMI ID or SSM Parameter expression to use to retrieve the AMI ID for the build server. Must be compatible with operating system version used by ECS cluster.
          default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Core-ECS_Optimized/image_id
        build_server_instance_type:
          default: t2.medium
          enum: [t2.small, t2.medium, t2.large, 
                 t3.small, t3.medium, t3.large,
                 t3a.small, t3a.medium, t3a.large ]
        build_server_volume_type:
          type: number
          default: 30
          minimum: 4
          maximum: 1024
        build_server_volume_size:
          type: string
          default: gp3
          enum: [ gp3, gp2 ]
        dockerfile:
          type: string
          description: "The location of the Dockerfile to build"
          default: "Dockerfile"
          minLength: 1
          maxLength: 100
