proton: ServiceSpec

pipeline:
  build_server_instance_type: "t3.medium"

instances:
  - name: "frontend-dev"
    environment: "Beta"
    spec:
      desired_count: 2
      port: 80
      task_size: "medium"
      service_discovery_name: "frontend-dev"
