schema:
  format:
    openapi: "3.0.0"
  service_input_type: "CrudServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    CrudServiceInput:
      type: object
      description: "Input properties for a Lambda data processing service."
      properties:
        resource_name:
          type: string
          description: "The resource to generate a CRUD API for"
          minLength: 1
          maxLength: 50
          default: "task"
        callback_handler:
          type: string
          description: "The path for the handler responsible for callbacks"
          minLength: 1
          maxLength: 50
          default: "callback.handler"
        stream_handler:
          type: string
          description: "The path for the handler responsible for kinesis stream"
          minLength: 1
          maxLength: 50
          default: "stream.handler"
        lambda_memory:
          type: number
          description: "The size of your Lambda functions in MB"
          default: 512
          minimum: 1
          maximum: 3008
        lambda_timeout:
          type: number
          description: "The timeout in seconds of your Lambda function"
          default: 30
          minimum: 1
          maximum: 900
        lambda_runtime:
          type: string
          description: "The runtime for your Lambda service"
          enum: ["nodejs12.x", "python3.8", "ruby2.7", "java11", "go1.x", "dotnetcore3.1"]
          default: "ruby2.7"
        code_uri:
          type: string
          description: "The s3 link to your application"
          minLength: 1
          maxLength: 200

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        unit_test_command:
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
        packaging_command:
          type: string
          description: "The commands which packages your code into a file called function.zip"
          default: "make publish"
          minLength: 1
          maxLength: 200
        environment_account_ids:
          type: string
          pattern: '^$|^\d{12}(,\d{12})*$'
          description: "The environment account ids for service instances using cross account environment, separated by ,"
          default: ""
          maxLength: 200

